apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: curious-ape
resources:
  - ../../base
  - env.yaml
  - HTTPRoute.yaml

secretGenerator:
  - name: ape-litestream
    files: [secrets/litestream.yaml]
  - name: ape-config
    files: [secrets/config.json]
